name: flutter_xmlrpc
version: 0.0.2
author: BUSINESS IT SYSTEMS <ashish@busits.com>
description: A library to communicate through the XML-RPC protocol.
homepage: https://github.com/busits/flutter-xmlrpc
website: https://busits.com/

environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  meta: ^1.1.5
  xml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
